logging:
  level:
    org.springframework: info

spring:
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:
      jdbc-url: jdbc:h2:tcp://localhost/~/test

  messages:
    basename: messages

  security:
    user:
      name: user
      password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'